### ISSUE TITLE
Put a Changelog on the F-Droid Release.

### ISSUE THREAD

**Issue by locutis-of-borg-1999** [ninelima/kwikEFIS#1]
The F-Droid release (https://f-droid.org/app/player.efis.pfd) does not have a changelog linked.  

By the way, this is good work.  Great for in tne cockpit, and maybe for UAVs, too.

**Comment by locutis-of-borg-1999** [comment]
It is not on that page above, and therefore not on the information page in the F-Droid application.

**Comment by ninelima** [comment]
Thanks. CHANGELOG.md added to github repository as:
https://github.com/ninelima/kwikEFIS/blob/master/CHANGELOG.md

Do you wish me to update the metadata for player.efis.pfd and submit a merge request?

**Comment by ninelima** [comment]
Changelog entry changed to:
Changelog:https://github.com/ninelima/kwikEFIS/blob/HEAD/CHANGELOG.md
