### ISSUE TITLE
Terrain file error zar.aus/W020N90

### ISSUE THREAD

**Issue by stemy2** [ninelima/kwikEFIS#10]
Hello,

I installed the app and all the datapacks from f-droid, but i have the error message mentioned in the title with 2 big red crosses on the screen.

**Comment by ninelima** [comment]
Have a look at this faq:
http://members.iinet.net.au/~ninelima/efis/faq.html
Where, in the world, are you trying to use the app?

**Comment by stemy2** [comment]
In Belgium. And i don't see any menu button. I'm on Galaxy S7.

**Comment by ninelima** [comment]
It looks like Samsung has "improved" Android on their Galaxy S7 to the point where it is no longer working like all other Android devices.
Google "missing menu button samsung s7", maybe you can get some way around it.

**Comment by stemy2** [comment]
I searched in the parameters and i found an option «Activate navigation bar», so the menu button can appear. It would be b nice enhancement if the app would support directly the phones with physical buttons.

**Comment by ninelima** [comment]
Excellent. I am glad you got it working. Please let me know the links and I will put that on the faq for other users with the same problem.

**Comment by stemy2** [comment]
I'm using a custom ROM, i don't know if the option is present in the parameters of the default android OS. Just in case, i describe the steps: phone parameters => Buttons = > Activate navigation bar.

**Comment by ninelima** [comment]
Thanks. I will update the faq.

**Comment by ninelima** [comment]
Enhancement: Once you have had opportunity to play a bit with Kwik EFIS, please let me know your ideas/ suggestions on activating a menu. 
Perhaps open a new issue on that subject, that way it will make it formally into the development cycle.

**Comment by stemy2** [comment]
I reopn the issue. After a reset of my phone, the problem reappeared, and now, i have the error even with EUR/RUS data. In addition, the app shouts indefinitely «STALL STALL STALL».

**Comment by ninelima** [comment]
You need a valid GPS fix. Check the GPS xx/yy reading. It should say something like "GPS 7/11" before the output will be stable. The warnings go a bit crazy until there is a solid GPS fix.
Once you have a GPS fix you can expect something like this:
![image](https://user-images.githubusercontent.com/17928961/29525707-21d55c4e-86c6-11e7-8e78-c5a274b74550.png)
And once there is a valid speed and/or direction the red X's should clear as well.
To practice with the app without the GPS use: Menu/Manage/Demo
See **Demo Mode**
http://members.iinet.net.au/~ninelima/efis/about.html

**Comment by ninelima** [comment]
EUR/RUS data:
Check the setting under Menu/Manage/Geographic Region  is set to "Europe/Russia"

**Comment by ninelima** [comment]
* I have had another look at introducing some automation with the DEM.
* Also added a bit of code to disable the alerts if there is not a valid GPS fix.

You can get  version 3.4 beta here: http://members.iinet.net.au/~ninelima/efis/download.html

**Comment by ninelima** [comment]
Addressed in VER_3.4 tagged release.
https://github.com/ninelima/kwikEFIS/releases/tag/VER_3.4
