### ISSUE TITLE
Map on website very old

### ISSUE THREAD

**Issue by theScrabi** [ninelima/kwikEFIS#11]
The map on your website [here](http://members.iinet.net.au/~ninelima/efis/img/gtopo30_index.png) is so old it still shows a splited  germany this however is not true anymore for more than 25 years now.

**Comment by ninelima** [comment]
Wow, thanks Christian. I did not have any idea! My knowledge of European 
geography and  politics is very limited.

If you can edit the map (gtopo30_index.png)... even an approximation 
using mspaint (or something similar) and  submit a merge request, I will 
be grateful. I will incorporate it into the next release.

Best wishes
Dave.



------ Original Message ------
