### ISSUE TITLE
Unable to choose a colour and sketch style.

### ISSUE THREAD

**Issue by Sammaz2** [ninelima/kwikEFIS#13]
### Actual behavior
I opened the quick draw opensource android app. Then after that i clicked on the pencil, that is for drawing. After that i started drawing something and then i clicked on option ,which is present on the bottom of the page and then i tried to choose a colour by clicking on colour icon and then i tried to change the sketch size or font size. But unfortunately I wasn't able to open anyone of the two options.

### How to reproduce

* First you need to download the app from fdroid and install it. After that open the app.

* Click on the pencil icon to draw something.

* Draw something and then click on the options present on the bottom of the page.

* After that click on the colour icon and so on size or style icon, but unfortunately you will not be able to open anyone of them.

https://youtu.be/3j-MQgTVteg

* Browser: Quick draw everywhere.

* Version:1.9

* Operating system:7.1.2

* Device model:Redmi 4

**Comment by ninelima** [comment]
Issued against incorrect project.
