### ISSUE TITLE
Datapac links broken

### ISSUE THREAD

**Issue by cessna151** [ninelima/kwikEFIS#8]
The links to download the datapac for synthetic vision don't work.
:large_orange_diamond:

**Comment by ninelima** [comment]
Hello cessna151,

Nice to hear from you and thanks for the feedback.

There has been a minor delay with publication of the data pacs on F-Droid. They should be available very soon.

In the mean time you can get the same files (but unsigned) under *"Current Release Candidates"
*http://members.iinet.net.au/~ninelima/efis/download.html

Kwik EFIS Support.
