### ISSUE TITLE
Terrain file Error?

### ISSUE THREAD

**Issue by df1paw** [ninelima/kwikEFIS#9]
Hello.
It seems there's an issue with the eur.rus terrain file: W020N40
See attached screenshot.
I tried with https://f-droid.org/repository/browse/?fdid=player.efis.data.eur.rus and also with http://members.iinet.net.au/~ninelima/efis/kwik-efis-datapac-eur.rus.apk - the problem actually affects both...

Thank you and 
kind regards,
  Andreas Weller
![screenshot_20170627-230940](https://user-images.githubusercontent.com/2004708/27632830-3b15ca16-5bfd-11e7-8e3e-0c09e46515c7.png)

**Comment by ninelima** [comment]
Hello Andreas, 

Thanks for the feedback. It looks like the GPS location shows N0.00, E0.00 (ie Null Island). When the GPS has a valid location and assuming you are in the area covered by eur.rus the terrain should load.
You need version 3.2 of Kwik EFIS (player.efis.pfd) which is not yet available on F-Droid. I expect it in the next few days. In the mean time try with: http://members.iinet.net.au/~ninelima/efis/kwik-efis.apk

**Comment by ninelima** [comment]
What is your geographic coordinates? I will use the test rig and let you know if it works or not.

**Comment by ninelima** [comment]
Once you have a GPS fix, enable the "Demo Mode" and check that the terrain loads properly.
I only tested in the Innsbruck area.

**Comment by ninelima** [comment]
Check that the Menu/Manage/Geograpic Region is set to the correct region as well.
This will probably become automatic in later versions. But it is useful for testing to set the regionmanually.
